#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_






/* System Clock */

#define F_CPU                    16000000UL

/* USART1_Configuration */

#define USART1_STATUS            USART1_ENABLE


#define USART1_BAUD_RATE         (u32)9600



#define USART1_WORD_LENGTH       _8BIT_WORD_LENGTH
#define USART1_PARITY            PARITY_DISABLE
#define USART1_INTERRUPT         INT_DISABLE

#define USART1_TRANSMITTER       TRANSMITTER_ENABLE
#define USART1_RECEIVER          RECEIVER_ENABLE

#define USART1_STOP_BITS         ONE_STOP_BIT











#define UART3_STATE UART_STATE_ENABLE

#define UART3_RECEIVER_STATE UART3_RECEIVER_STATE_ENABLE

#define UART3_TRANSMITTER_STATE UART3_TRANSMITTER_STATE_ENABLE

#define UART3_BAUDRATE UART3_BAUDRATE_9600

#define UART3_PARITY_STATE UART3_PARITY_STATE_DISABLE

#define UART3_STOP_BITS_MODE UART3_STOP_BITS_MODE_1

#define UART3_RECEIVE_INTERRUPT UART3_RECEIVE_INTERRUPT_ENABLE

#define UART3_TRANSMIT_INTERRUPT UART3_TRANSMIT_INTERRUPT_DISABLE

#define UART3_WORD_LENGTH UART3_WORD_LENGTH_8

#endif
